#
# mkdocs.yml.txt -- documentation for Molko's Engine
#
# Copyright (c) 2020-2026 David Demelier <markand@malikania.fr>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

site_name: Molko's Engine
theme: material
markdown_extensions:
  - admonition
  - tables
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
nav:
  - Home: index.md
  - About: about.md
  - Specifications:
    - map: specs/map.md
    - tileset: specs/tileset.md
  - Tools:
    - mlk-bcc: tools/bcc.md
    - mlk-map: tools/map.md
    - mlk-tileset: tools/tileset.md
  - Developer corner:
    - Notes:
      - Error handling: dev/error.md
      - Ownership: dev/ownership.md
      - FAQ: dev/faq.md
    - Howto:
      - dev/howto/01-init.md
    - C API Reference:
      - libmlk-core:
        - action: dev/api/core/action.md
        - alloc: dev/api/core/alloc.md
        - animation: dev/api/core/animation.md
        - clock: dev/api/core/clock.md
        - color: dev/api/core/color.md
        - core: dev/api/core/core.md
        - drawable: dev/api/core/drawable.md
        - error: dev/api/core/error.md
        - event: dev/api/core/event.md
        - font: dev/api/core/font.md
        - game: dev/api/core/game.md
        - image: dev/api/core/image.md
        - inhibit: dev/api/core/inhibit.md
        - key: dev/api/core/key.md
        - maths: dev/api/core/maths.md
        - mouse: dev/api/core/mouse.md
        - music: dev/api/core/music.md
        - painter: dev/api/core/painter.md
        - panic: dev/api/core/panic.md
        - save: dev/api/core/save.md
        - script: dev/api/core/script.md
        - sound: dev/api/core/sound.md
        - sprite: dev/api/core/sprite.md
        - state: dev/api/core/state.md
        - sys: dev/api/core/sys.md
        - texture: dev/api/core/texture.md
        - trace: dev/api/core/trace.md
        - translate: dev/api/core/translate.md
        - util: dev/api/core/util.md
        - window: dev/api/core/window.md
        - zfile: dev/api/core/zfile.md
    - Javascript API Reference:
      - Core:
        - animation: dev/jsapi/core/animation.md
